### ISSUE TITLE
"indian-diabetes-example" is broken

### ISSUE THREAD

**Issue by krystianhub** [nidhaloff/igel#26]
* igel version: 0.2.4
* Python version: 3.8.5
* Operating System: MacOS Catalina (version 10.15.7)

### Description

I have tried to run one of the examples (**indian-diabetes-example**) right after the installation.
Sadly, the program crashes because of the errors in **pandas** library (1.1.1).

### What I Did

```bash
pip3 install -U igel
git clone https://github.com/nidhaloff/igel
cd ./igel/examples/indian-diabetes-example
python3 ./fit.py
```

```
INFO - Entered CLI args: {'data_path': '../data/indian-diabetes/train-indians-diabetes.csv', 'yaml_path': './neural-network.yaml', 'cmd': 'fit'}
INFO - Executing command: fit ...
INFO - reading data from ../data/indian-diabetes/train-indians-diabetes.csv
INFO - You passed the configurations as a yaml file.
INFO - your chosen configuration: {'model': {'type': 'classification', 'algorithm': 'Ridge'}, 'target': ['sick']}
INFO - dataset_props: {'type': 'csv', 'read_data_options': 'default', 'split': {'test_size': 0.2, 'shuffle': True, 'stratify': 'default'}, 'preprocess': {'missing_values': 'mean', 'scale': {'method': 'standard', 'target': 'inputs'}}} 
model_props: {'type': 'classification', 'algorithm': 'Ridge'} 
 target: ['sick'] 

ERROR - error occured while preparing the data: ('read_csv() argument after ** must be a mapping, not str',)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/igel/igel.py", line 189, in _process_data
    dataset = pd.read_csv(self.data_path) if not read_data_options else pd.read_csv(self.data_path,
TypeError: read_csv() argument after ** must be a mapping, not str
Traceback (most recent call last):
  File "./fit.py", line 23, in <module>
    Igel(**mock_fit_params)
  File "/usr/local/lib/python3.8/site-packages/igel/igel.py", line 88, in __init__
    getattr(self, self.command)()
  File "/usr/local/lib/python3.8/site-packages/igel/igel.py", line 320, in fit
    x_train, y_train, x_test, y_test = self._prepare_fit_data()
TypeError: cannot unpack non-iterable NoneType object
```

**Comment by nidhaloff** [comment]
@krystianhub Thanks for noticing this. I just fixed it. It was showing the error because I forgot to update the example after the last release.
